### ISSUE TITLE
Info for ERROR 29381 

### ISSUE THREAD

**Issue by teopost** [cronn-de/jira-sync#4]
Hi,
 I try to sync 2 jira projects with jira-sync but I have an error that I can not understand.

![image](https://user-images.githubusercontent.com/2573389/36634955-22085cc8-19ad-11e8-9d9b-c7094f284d10.png)

Is a very generic error!
Can you help me understand what I'm wrong?

**Comment by ldziedziul** [comment]
Hi Stefano, 

Could you provide a full stacktrace and re-run application with `--debug`?

**Comment by teopost** [comment]
Yes,
This is the complete output  [log.txt](https://github.com/cronn-de/jira-sync/files/1755268/log.txt)

**Comment by ldziedziul** [comment]
Thanks!

Your log helped me a lot. You can see there a `JiraResourceNotFoundException`. The stacktrace indicates that there is a problem with the source filter settings:
```
de.cronn.jira.sync.projects[XXXX].sourceFilterId=<filterId>
```
Please double check that `<filterId>` points to the existing filter in your source Jira.

BTW. We need to improve our exceptions to be more descriptive ;)

**Comment by teopost** [comment]
My filterId is "allopenissues"

![image](https://user-images.githubusercontent.com/2573389/36635527-ed013bbc-19b6-11e8-881f-7bd143b0292c.png)

**Comment by teopost** [comment]
Hi @ldziedziul , I have created a custom filter.
Now the error is different (I think):
![image](https://user-images.githubusercontent.com/2573389/36635570-c12d5434-19b7-11e8-94a1-640b2e105d7c.png)

**Comment by ldziedziul** [comment]
I see. We've used custom filters so far which have always numeric id, `allopenissues` is a special case. A custom filter should resolve it. 

Please send the log file with the full stacktrace again. This time without `--debug`

**Comment by teopost** [comment]
I think the problem is here:
![image](https://user-images.githubusercontent.com/2573389/36635662-912695c8-19b9-11e8-887e-2499715a91ca.png)
but I don't have this field (I think) in the destination screen.
sorry but I don't know how to setting parameters in application.properties.
Can you explain the parameters of application.properties file ?

**Comment by ldziedziul** [comment]
I'm guessing without a stacktrace but currently we allways fetch the following fields using filters: `summary,status,issuetype,description,priority,project,resolution,labels,versions,fixVersions,assignee,updated,comment`

It looks like that for some reason you don't have `versions` and `fixVersions` fields which, we thought, are built-in (https://confluence.atlassian.com/adminjiraserver071/issue-fields-and-statuses-802592413.html). 

Could you try to add a "1.0" version on both side to see if it helps? 

You don't have to add the following lines to application.properties:
```
de.cronn.jira.sync.projects[XXX].versionMapping....
```
and 
```
de.cronn.jira.sync.projects[XXX].versionsToIgnore=Undefined
```
Version mapping is optional. 

Background:
These lines are used if you have different versions in both jira servers, e.g. 
```
de.cronn.jira.sync.projects[XXX].versionMapping[10.0]=10
```
means that you have version `10.0` in the source server and it has the same meaning as version `10 ` on the target server. If you don't configure `versionMapping` it will be omitted.

**Comment by teopost** [comment]
I have added Version 1.0 on both side but the result is the same.

[log2.txt](https://github.com/cronn-de/jira-sync/files/1755919/log2.txt)

[application.properties.txt](https://github.com/cronn-de/jira-sync/files/1755920/application.properties.txt)

Executed with this command line:
```
./build/libs/jira-sync-1.0.jar --spring.config.location=file:/Users/teopost/dev/jira-sync/config/application.properties
```
Some other info: The destination project is "Service Desk" type

**Comment by ldziedziul** [comment]
Hi. I've pushed the fix, please try now.

**Comment by teopost** [comment]
Thank you. Now work!
