### ISSUE TITLE
How to change status to source project

### ISSUE THREAD

**Issue by teopost** [cronn-de/jira-sync#5]
Hi,
  I have this configuration:

**Source project:**
![image](https://user-images.githubusercontent.com/2573389/36695726-6bd8056a-1b42-11e8-879e-f50e4fd8ba64.png)
**Target project:** 
![image](https://user-images.githubusercontent.com/2573389/36695783-9263647c-1b42-11e8-9fd1-1fddda924c62.png)

When I execute jira-sync a new issue has been created correctly to the destination project.
I would like to change source status to In Progress.
Can you suggest which configuration I can do for this ?

This is my failed try
```
de.cronn.jira.sync.projects[SDFER].transitions[InCarico].sourceStatusToSet=In Progress
```
Thanks

**Comment by ldziedziul** [comment]
Hi @teopost,

Transitions are applied only for issues existing on the both sides. You could try configure jira-sync in the following matter:
```
# when
de.cronn.jira.sync.projects[SDFER].transitions[InCarico].sourceStatusIn=Todo
de.cronn.jira.sync.projects[SDFER].transitions[InCarico].targetStatusIn=Waiting For Triage
# then
de.cronn.jira.sync.projects[SDFER].transitions[InCarico].sourceStatusToSet=In Progress
```
On the first pass jira-sync will create the source issue in the target jira and on the next pass it will set status of the source issue to` In Progress`. 

BTW `InCarico` from `transitions[InCarico]` is used only as a key in the configuration file, it has nothing in common with transitions from jira workflow

**Comment by ldziedziul** [comment]
Hi @teopost,

Does it work the way I've suggested?

**Comment by teopost** [comment]
No @ldziedziul , the source issue remain in TO DO status.
Attach the log of the second execution.
[log.txt](https://github.com/cronn-de/jira-sync/files/1800809/log.txt)

> BTW InCarico from transitions[InCarico] is used only as a key in the configuration file, it has nothing in common with transitions from jira workflow
I don't understand the syntax logic
