### ISSUE TITLE
Issue with caching by #root.target.url

### ISSUE THREAD

**Issue by vitaliy-sk** [cronn-de/jira-sync#6]
For some methods #root.target.url (java.net.URL) used as the cache key in ehcache

```java
@Cacheable(value = CACHE_NAME_SERVER_INFO, key = "#root.target.url")
public JiraServerInfo getServerInfo()
```

The issue that java.net.URL#hashCode is based on [IP address](https://stackoverflow.com/questions/2348399/why-does-java-net-urls-hashcode-resolve-the-host-to-an-ip), so in some cases (for example with cloud JIRA), hashcode for two different JIRA's can be the same.

This is causing unpredictable issues, for example for me sometimes it's duplicating issues because `JiraIssueWebLinker` working incorectly

**Comment by bwaldvogel** [comment]
Thanks for spotting this issue!

You removed your previous description regarding Spring bean injection on purpose?

**Comment by vitaliy-sk** [comment]
`You removed your previous description regarding Spring bean injection on purpose?`

yes, because I was wrong, the root cause it's hashCode implementation in java.net.URL

**Comment by bwaldvogel** [comment]
Can you verify if my fix solves your issue?

**Comment by vitaliy-sk** [comment]
Many thanks Benedikt, yes with String it working fine

**Comment by vitaliy-sk** [comment]
Benedikt, sorry for confusing but looks like the field URL in [JiraServiceRestClient](https://github.com/cronn-de/jira-sync/blob/956d4811f5dc0452be42f65dfd48829013135a76/src/main/java/de/cronn/jira/sync/service/JiraServiceRestClient.java#L83) still `java.net.URL`.

So it means that ehcache continue use URL.hashCode()

**Comment by bwaldvogel** [comment]
Sorry, my bad. This should be fixed now. Could you give it another try?

**Comment by vitaliy-sk** [comment]
Thanks for the very fast fix, working fine.
